#!/bin/bash

SOURCE_DIR=../bitdust.docs.english

for mdfilepath in $SOURCE_DIR/*.md
do

    mdfile=$(basename "$mdfilepath")
    htmlfile="${mdfile/.md/.html}"
    python md2html.py "$SOURCE_DIR/$mdfile" > "./$htmlfile"
    python fix_html.py "./$htmlfile" "./$htmlfile"
    echo "$SOURCE_DIR/$mdfile -> ./$htmlfile"
done


